[package]
name = "ruty"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bit-vec = "0.8.0"
num-traits = "0.2.19"
num-bigint = "0.4.6"
ordered-float = "4.6.0"

[dev-dependencies]
pretty_assertions = "1.4.1"

[workspace]
members = ["ext/ruty", "lsp"]
